FROM node:18-alpine AS base

FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --legacy-peer-deps

FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ARG NEXT_PUBLIC_APP_BASE_URL
ARG NEXT_PUBLIC_VNP_API
ARG NEXT_PUBLIC_VNP_RETURNURL
ARG NEXT_PUBLIC_VNP_TMNCODE
ENV NEXT_PUBLIC_APP_BASE_URL=$NEXT_PUBLIC_APP_BASE_URL
ENV NEXT_PUBLIC_VNP_API=$NEXT_PUBLIC_VNP_API
ENV NEXT_PUBLIC_VNP_RETURNURL=$NEXT_PUBLIC_VNP_RETURNURL
ENV NEXT_PUBLIC_VNP_TMNCODE=$NEXT_PUBLIC_VNP_TMNCODE
RUN npm run build

FROM base AS runner
WORKDIR /app
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
USER nextjs
EXPOSE 3000
ENV PORT 3000
CMD ["node", "server.js"]
